# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: AKV"
$Body = @'
{
  "BlueprintAllowed": false,
  "Capability": "AKV",
  "CustomAliasAllowed": "Required",
  "EntryParameters": [
    {
      "Name": "CertificateTags",
      "DisplayName": "Certificate Tags",
      "Description": "If desired, tags can be applied to the KeyVault entries.  Provide them as a JSON string of key-value pairs ie: '{'tag-name': 'tag-content', 'other-tag-name': 'other-tag-content'}'",
      "Type": "string",
      "DefaultValue": "",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "PreserveExistingTags",
      "DisplayName": "Preserve Existing Tags",
      "Description": "If true, this will perform a union of any tags provided with enrollment with the tags on the existing cert with the same alias and apply the result to the new certificate.",
      "Type": "Bool",
      "DefaultValue": "False",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    },
    {
      "Name": "NonExportable",
      "DisplayName": "Non Exportable Private Key",
      "Description": "If true, this will mark the certificate as having a non-exportable private key when importing into Azure KeyVault",
      "Type": "Bool",
      "DefaultValue": "False",
      "RequiredWhen": {
        "HasPrivateKey": false,
        "OnAdd": false,
        "OnRemove": false,
        "OnReenrollment": false
      }
    }
  ],
  "JobProperties": [],
  "LocalStore": false,
  "Name": "Azure Keyvault",
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default"
  },
  "PowerShell": false,
  "PrivateKeyAllowed": "Optional",
  "Properties": [
    {
      "Name": "SkuType",
      "DisplayName": "SKU Type",
      "Description": "The SKU type for newly created KeyVaults (only needed if needing to create new KeyVaults in your Azure subscription via Command)",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "standard,premium",
      "Required": false
    },
    {
      "Name": "VaultRegion",
      "DisplayName": "Vault Region",
      "Description": "The Azure Region to put newly created KeyVaults (only needed if needing to create new KeyVaults in your Azure subscription via Command)",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "eastus,eastus2,westus2,westus3,westus",
      "Required": false
    },
    {
      "Name": "AzureCloud",
      "DisplayName": "Azure Cloud",
      "Description": "The Azure Cloud where the KeyVaults are located (only necessary if not using the standard Azure Public cloud)",
      "Type": "MultipleChoice",
      "DependsOn": "",
      "DefaultValue": "public,china,government",
      "Required": false
    },
    {
      "Name": "PrivateEndpoint",
      "DisplayName": "Private KeyVault Endpoint",
      "Description": "The private endpoint of your vault instance (if a private endpoint is configured in Azure)",
      "Type": "String",
      "DependsOn": "",
      "Required": false
    }
  ],
  "ServerRequired": true,
  "ShortName": "AKV",
  "StorePathType": "",
  "StorePathValue": "",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  }
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

